modLoader="javafml"
loaderVersion="[0,)"
license="LGPLv3"
issueTrackerURL="https://github.com/huskcasaca/effortless/issues"

[[mods]]
modId="effortless"
version="3.2.0"
displayName="Effortless Structure"
updateJSONURL=""
displayURL="https://modrinth.com/mod/effortless"
logoFile="assets/effortless/icon.png"
credits=""
authors="Huskcasaca"
displayTest="MATCH_VERSION"
description='''It just saves your time.'''

[[dependencies.effortless]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.effortless]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
